site_name: Arborist
nav:
  - Home: index.md
  - Installation: installation.md
  - CLI Tool: usage.md 
  - Package Tutorial: package-tutorial.md 
theme:
  name: material
  palette:
    primary: green
    accent: brown